### PR TITLE
Bump to GitBucket 4.32.0

### PR DESCRIPTION
**Pull request by SIkebe**
* scala 2.13.0
* GitBucket 4.32.0
* sbt 1.2.8

### CODE REVIEW

**Comment by SIkebe** [comment]
@jyuch Hmm... it successfully compiled with Scala 2.13. However, when I reload this plugin, I get below errors. Am I missing something?
```
16:39:53.004 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-backup-plugin_2.13-1.2.1.jar
16:39:53.135 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
16:39:53.135 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.3.0 created.
16:39:53.143 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
16:39:53.147 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.3.0) 'QuartzScheduler~backup' with instanceId 'backup'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

16:39:53.148 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler 'QuartzScheduler~backup
16:39:53.148 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler version: 2.3.0
16:39:53.150 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler~backup_$_backup started.
[INFO] [08/15/2019 16:39:53.163] [main] [[QuartzScheduler~backup]] Initialized calendars: 
[INFO] [08/15/2019 16:39:53.173] [main] [[QuartzScheduler~backup]] Setting up scheduled job 'Backup', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@328572f0'
Uncaught error from thread [backup-akka.actor.default-dispatcher-5]: com/amazonaws/auth/AWSCredentials, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[backup]
java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials
 at io.github.gitbucket.backup.actor.FinishingActor.receive(FinishingActor.scala:27)
 at akka.actor.ActorCell.newActor(ActorCell.scala:654)
 at akka.actor.ActorCell.create(ActorCell.scala:674)
 at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
 at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
 at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
 at akka.dispatch.Mailbox.run(Mailbox.scala:228)
 at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
 at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentials
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 12 more
[ERROR] [SECURITY][08/15/2019 16:39:53.229] [backup-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(backup)] Uncaught error from thread [backup-akka.actor.default-dispatcher-5]: com/amazonaws/auth/AWSCredentials, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[backup]
java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials
 at io.github.gitbucket.backup.actor.FinishingActor.receive(FinishingActor.scala:27)
 at akka.actor.ActorCell.newActor(ActorCell.scala:654)
 at akka.actor.ActorCell.create(ActorCell.scala:674)
 at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
 at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
 at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
 at akka.dispatch.Mailbox.run(Mailbox.scala:228)
 at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
 at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentials
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 12 more
```

**Comment by SIkebe** [comment]
backup.conf
```
# Backup timing (Required)
# For details, see http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html
# This example, backup 12am every day
akka {
  quartz {
    schedules {
      Backup {
        expression = "0 0 0 * * ?"
      }
    }
  }
}

backup {
  # Backup archive destination directory (Optional)
  # If not specified, archive is saved into GITBUCKET_HOME
  #archive-destination = """/path/to/archive-dest-dir"""

  # Maximum number of backup archives to keep (if 0 or negative value, keep unlimited) (Optional)
  # If not specified, keep unlimited
  #archive-limit = 10

  # Send notify email when backup is success (Optional, default:false)
  #notify-on-success = true

  # Send notify email when backup is failure (Optional, default:false)
  #notify-on-failure = true

  # Notify email destination (Optional)
  #notify-dest = ["jyuch@localhost"]

  # S3 compatible object storage for backup upload (Optional)
#  s3 {
#    # Endpoing URL
#    endpoint = "http://localhost:9000"
#
#    # Region
#    region = "US_EAST_1"
#
#    # Access key
#    access-key = "access-key"
#
#    # Secret key
#    secret-key = "secret-key"
#
#    # Bucket of backup destination
#    bucket = "gitbucket"
#  }
}
```

**Comment by jyuch** [comment]
Maybe this error meaning missing AWS S3 SDK.

Did you use `sbt assembly` when compile plugin?

**Comment by SIkebe** [comment]
Ah, thanks! I used `sbt package`. `sbt assembly` works.

@jyuch Could you review this PR?

**Comment by jyuch** [comment]
@SIkebe Thanks!!

**Pull request merged**
